filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
    - /tmp/var/logs/nginx-access*
    fields:
      type: nginx-access-log
  - type: log
    enabled: true
    paths:
    - /tmp/var/logs/hro-*
    fields:
      type: hro-app-log
    multiline.type: pattern
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after

processors:
  - add_host_metadata: ~

output.kafka:
  enabled: true
  hosts: 
  - kafka1:29092
  topic: '%{[fields.type]}'